name: Daily Run IPTV Script

on:
  schedule:
    # 每天午夜（0点）触发工作流
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python iptv_join.py

      - name: Update output
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update output - $(date +"%Y-%m-%d %H:%M:%S")"
          git push